# Source Config
sink.datasource=kafka
sink.storage.mode=stream
sink.datasource.rate.limit=-1

# Kafka Config
bootstrap.servers=pixels_kafka:9092
group.id=docker-pixels-table
auto.offset.reset=earliest
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
sink.kafka.value.format=json

# Topic & Database Config
topic.prefix=oltp_server
consumer.capture_database=pixels_realtime_crud
consumer.include_tables=

# Sink Config
sink.mode=retina
sink.csv.path=./data
sink.csv.enable_header=false

# Retina Config
sink.retina.mode=stream
sink.retina.client=4
sink.retina.log.queue=false
sink.remote.host=localhost
sink.remote.port=29422
sink.timeout.ms=5000
sink.flush.interval.ms=1000
sink.flush.batch.size=100
sink.max.retries=3
sink.commit.method=sync
sink.commit.batch.size=100
sink.commit.batch.worker=8
sink.commit.batch.delay=1000

## Schema Registry
sink.registry.url=http://apicurio:8080/apis/registry/v2

# Transaction Config
transaction.topic.suffix=transaction
transaction.topic.group_id=transaction_consumer
sink.trans.batch.size=100
sink.trans.mode=batch
transaction.timeout=300

# Sink Metrics
sink.monitor.enable=true
sink.monitor.port=9464

# Interact with other rpc
sink.rpc.enable=false
