CREATE TABLE records
(
    id BIGINT NOT NULL PRIMARY KEY,
    sequence_no INT NULL,
    boolean_value BOOLEAN NULL,
    tiny_value TINYINT NULL,
    small_value SMALLINT NULL,
    int_value INT NULL,
    big_value BIGINT NULL,
    float_value FLOAT NULL,
    double_value DOUBLE NULL,
    decimal_value DECIMAL(18, 4) NULL,
    char_value CHAR(4) NULL,
    varchar_value VARCHAR(64) NULL,
    text_value TEXT NULL,
    binary_value BINARY(4) NULL,
    varbinary_value VARBINARY(8) NULL,
    blob_value BLOB NULL,
    date_value DATE NULL,
    time_value TIME(3) NULL,
    timestamp_value DATETIME(6) NULL,
    unicode_value VARCHAR(64) NULL,
    nullable_value VARCHAR(64) NULL,
    json_value JSON NULL,
    enum_value ENUM ('RED', 'GREEN', 'BLUE') NULL,
    set_value SET ('ALPHA', 'BETA', 'GAMMA') NULL
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

INSERT INTO records
VALUES (1001,
        0,
        TRUE,
        -7,
        -1234,
        -123456789,
        -1234567890123456789,
        1.25,
        -12345.5,
        12345678901234.5678,
        'ABCD',
        'snapshot-varchar',
        'snapshot-text',
        X'000102FF',
        X'DEADBEEF',
        X'00FF10',
        '2024-02-29',
        '12:34:56.789',
        '2024-02-29 12:34:56.123456',
        '像素-快照🌟',
        NULL,
        '"json-snapshot"',
        'GREEN',
        'ALPHA,GAMMA');
