# engine | kafka | storage
sink.datasource=storage
sink.storage.mode=stream
# CDC dialect for envelope normalization: mysql | postgresql
sink.debezium.dialect=postgresql
# -1 means no limit, Only implement in retina sink mode yet:
sink.datasource.rate.limit=200000
sink.monitor.report.file=/home/ubuntu/pixels-sink/result1k2_feb/rate_8192tile_3.csv
sink.monitor.freshness.file=/home/ubuntu/pixels-sink/result1k2_feb/fresh_8192tile_3.csv
# rate limiter implement: guava or semaphore
sink.datasource.rate.limit.type=guava
# Sink Config: retina | csv | proto | flink | none
sink.mode=retina
sink.retina.client=1
# in flight rpc
sink.retina.rpc.limit=100000
sink.retina.trans.limit=10000000
sink.retina.log.queue=false
sink.retina.trans.request.batch=true
sink.commit.method=async
sink.retina.trans.request.batch.size=100
## batch or single or record, batch is recommend. record is faster, but doesn't have ACID feature
sink.trans.mode=batch
sink.monitor.report.enable=true
# trino for freshness query
sink.query.url=jdbc:trino://realtime-pixels-coordinator:8080/pixels/pixels_bench
# sink.query.url=jdbc:trino://realtime-pixels-coordinator:8080/pixels/pixels_bench_sf10x
sink.query.user=pixels
sink.query.password=password
sink.query.parallel=1
# row or txn or embed
sink.monitor.freshness.level=embed
sink.monitor.freshness.verbose=true
sink.monitor.freshness.embed.warmup=10
sink.monitor.freshness.embed.static=false
sink.monitor.freshness.embed.snapshot=true
sink.monitor.freshness.embed.tablelist=loantrans
sink.monitor.freshness.embed.delay=10
# sink.monitor.freshness.embed.tablelist=savingaccount
sink.monitor.freshness.timestamp=true
sink.storage.loop=true
# Kafka Config
bootstrap.servers=realtime-kafka-2:29092
group.id=3078
auto.offset.reset=earliest
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
sink.kafka.value.format=json
# Topic & Database Config
topic.prefix=postgresql.oltp_server
consumer.capture_database=pixels_bench_sf1x
consumer.include_tables=
sink.csv.path=./data
sink.csv.enable_header=false
## Retina Config
sink.retina.embedded=false
# stub or stream
sink.retina.mode=stream
#writer.retina.mode=stub
sink.remote.host=localhost
sink.remote.port=29422
sink.timeout.ms=5000
sink.flush.interval.ms=5
sink.flush.batch.size=100
sink.max.retries=3
## writer commit
# sync or async
sink.commit.batch.size=100
sink.commit.batch.worker=4
sink.commit.batch.delay=10
## Proto Config
sink.proto.dir=file:///home/ubuntu/disk2/hybench/
sink.proto.data=hybench1000_4
# sink.proto.data=hybench100_3
# sink.proto.data=hybench100_4
# sink.proto.data=hybench10_10
sink.proto.maxRecords=100000
## Flink Config
sink.flink.server.port=9091
## Schema Registry
sink.registry.url=http://localhost:8080/apis/registry/v2
# Transaction Config
transaction.topic.suffix=transaction
sink.trans.batch.size=100

# Sink Metrics
sink.monitor.enable=true
sink.monitor.port=9464
sink.monitor.report.interval=1000
sink.monitor.freshness.interval=1000

# Interact with other rpc
sink.rpc.enable=true
# debezium engine config
debezium.name=testEngine
debezium.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.provide.transaction.metadata=true
debezium.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.offset.storage.file.filename=/tmp/offsets.dat
debezium.offset.flush.interval.ms=60000
debezium.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.schema.history.internal.file.filename=/tmp/schemahistory.dat
debezium.database.hostname=realtime-pg-2
debezium.database.port=5432
debezium.database.user=pixels
debezium.database.password=pixels_realtime_crud
debezium.database.dbname=pixels_bench
debezium.plugin.name=pgoutput
debezium.database.server.id=1
debezium.schema.include.list=public
debezium.snapshot.mode=never
debezium.key.converter=org.apache.kafka.connect.json.JsonConverter
debezium.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.topic.prefix=postgresql.oltp_server
debezium.transforms=topicRouting
debezium.transforms.topicRouting.type=org.apache.kafka.connect.transforms.RegexRouter
debezium.transforms.topicRouting.regex=postgresql\\.oltp_server\\.public\\.(.*)
debezium.transforms.topicRouting.replacement=postgresql.oltp_server.pixels_bench_sf10x.$1
