# engine | kafka | storage
sink.datasource=engine
sink.datasource.engine.format=connect
# CDC dialect for envelope normalization: mysql | postgresql
sink.debezium.dialect=postgresql
sink.storage.mode=stream
# -1 means no limit, Only implement in retina sink mode yet
sink.datasource.rate.limit=100000
# Sink Config: retina | csv | proto | flink | none
sink.mode=retina
sink.retina.client=8
sink.retina.log.queue=false
## batch or single or record, batch is recommend. record is faster, but doesn't have ACID feature
sink.trans.mode=batch
sink.monitor.report.enable=true
sink.monitor.report.file=/home/ubuntu/pixels-sink/resulti7i/100k_rate_2.csv
sink.monitor.freshness.file=/home/ubuntu/pixels-sink/resulti7i/100k_freshness_2.csv
# trino for freshness query
sink.query.url=jdbc:trino://realtime-kafka-2:8080/pixels/pixels_bench_sf10x
# sink.query.url=jdbc:trino://realtime-pixels-coordinator:8080/pixels/pixels_bench_sf10x
sink.query.user=pixels
sink.query.password=password
sink.query.parallel=8
# row or txn or embed
sink.monitor.freshness.level=embed
sink.monitor.freshness.embed.warmup=10
sink.monitor.freshness.embed.static=false
sink.monitor.freshness.embed.snapshot=true
sink.monitor.freshness.embed.tablelist=loanapps,loantrans
sink.monitor.freshness.verbose=true
sink.monitor.freshness.timestamp=true
sink.storage.loop=true
# Kafka Config
bootstrap.servers=realtime-kafka-2:29092
group.id=3078
auto.offset.reset=earliest
key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
sink.kafka.value.format=json
# Topic & Database Config
topic.prefix=postgresql.oltp_server
consumer.capture_database=pixels_bench_sf1x
consumer.include_tables=
sink.csv.path=./data
sink.csv.enable_header=false
## Retina Config
sink.retina.embedded=false
# stub or stream
sink.retina.mode=stream
#writer.retina.mode=stub
sink.remote.host=localhost
sink.remote.port=29422
sink.timeout.ms=5000
sink.flush.interval.ms=50
sink.flush.batch.size=10
sink.max.retries=3
## writer commit
# sync or async
sink.commit.method=sync
sink.commit.batch.size=10
sink.commit.batch.worker=32
sink.commit.batch.delay=3000
## Proto Config
sink.proto.dir=file:///home/ubuntu/disk1/hybench/
sink.proto.data=hybench10_10
sink.proto.maxRecords=100000
## Flink Config
sink.flink.server.port=9091
## Schema Registry
sink.registry.url=http://localhost:8080/apis/registry/v2
# Transaction Config
transaction.topic.suffix=transaction
sink.trans.batch.size=100

# Sink Metrics
sink.monitor.enable=true
sink.monitor.port=9464
sink.monitor.report.interval=10000
sink.monitor.freshness.interval=1000

# Interact with other rpc
sink.rpc.enable=true
# debezium engine config
debezium.name=testEngine
debezium.connector.class=io.debezium.connector.postgresql.PostgresConnector
debezium.provide.transaction.metadata=true
debezium.offset.storage=org.apache.kafka.connect.storage.FileOffsetBackingStore
debezium.offset.storage.file.filename=/tmp/offsets.dat
debezium.offset.flush.interval.ms=60000
debezium.schema.history.internal=io.debezium.storage.file.history.FileSchemaHistory
debezium.schema.history.internal.file.filename=/tmp/schemahistory.dat
debezium.database.hostname=realtime-pg-2
debezium.database.port=5432
debezium.database.user=pixels
debezium.database.password=pixels_realtime_crud
debezium.database.dbname=pixels_bench_sf10x
debezium.plugin.name=pgoutput
debezium.database.server.id=1
debezium.schema.include.list=public
debezium.snapshot.mode=never
debezium.key.converter=org.apache.kafka.connect.json.JsonConverter
debezium.value.converter=org.apache.kafka.connect.json.JsonConverter
debezium.topic.prefix=postgresql.oltp_server
debezium.transforms=topicRouting
debezium.transforms.topicRouting.type=org.apache.kafka.connect.transforms.RegexRouter
debezium.transforms.topicRouting.regex=postgresql\\.oltp_server\\.public\\.(.*)
debezium.transforms.topicRouting.replacement=postgresql.oltp_server.pixels_bench_sf10x.$1
