{
 "title": "Sink Server Monitoring",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "table",
    "query": "label_values(sink_table_changes_total, table)"
   }
  ]
 },
 "panels": [
  {
   "title": "Transaction Per Min",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(sink_transactions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TPM",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 7, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(sink_transactions_total[1m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table Changes Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 0 },
   "targets": [
    { "expr": "sink_table_changes_total{}", "legendFormat": "{{table}}" }
   ]
  },
  {
   "title": "Processing Latency",
   "type": "gauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.5\"}",
     "legendFormat": "50%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.75\"}",
     "legendFormat": "75%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.95\"}",
     "legendFormat": "95%"
    },
    {
     "expr": "sink_processing_latency_seconds{quantile=\"0.99\"}",
     "legendFormat": "99%"
    }
   ]
  },
  {
   "title": "Raw Data Throughput",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sink_data_throughput_counter_total",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Transaction Total Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 13, "x": 6, "y": 9 },
   "targets": [
    { "expr": "sink_transactions_total", "legendFormat": "Transaction Total Count" }
   ]
  },
  {
   "title": "Row Operations Distribution",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 19, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sink_row_changes_total) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  }
 ]
}