// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: transaction.proto

package io.pixelsdb.pixels.sink.proto;

public final class TransactionMetadataValue {
  private TransactionMetadataValue() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TransactionMetadataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.pixelsdb.pixels.sink.proto.TransactionMetadata)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    java.lang.String getStatus();
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    com.google.protobuf.ByteString
        getStatusBytes();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>int64 event_count = 3;</code>
     * @return The eventCount.
     */
    long getEventCount();

    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> 
        getDataCollectionsList();
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDataCollections(int index);
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    int getDataCollectionsCount();
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    java.util.List<? extends io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder> 
        getDataCollectionsOrBuilderList();
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder getDataCollectionsOrBuilder(
        int index);

    /**
     * <pre>
     * JSON中"optional": false对应非optional字段
     * </pre>
     *
     * <code>int64 ts_ms = 5;</code>
     * @return The tsMs.
     */
    long getTsMs();
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }

  /**
   * Protobuf type {@code io.pixelsdb.pixels.sink.proto.TransactionMetadata}
   */
  public static final class TransactionMetadata extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.pixelsdb.pixels.sink.proto.TransactionMetadata)
      TransactionMetadataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TransactionMetadata.newBuilder() to construct.
    private TransactionMetadata(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TransactionMetadata() {
      status_ = "";
      id_ = "";
      dataCollections_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TransactionMetadata();
    }

    private TransactionMetadata(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              status_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 24: {

              eventCount_ = input.readInt64();
              break;
            }
            case 34: {
              if ((mutable_bitField0_ & 0x00000001) == 0) {
                dataCollections_ = new java.util.ArrayList<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection>();
                mutable_bitField0_ |= 0x00000001;
              }
              dataCollections_.add(
                  input.readMessage(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.parser(), extensionRegistry));
              break;
            }
            case 40: {

              tsMs_ = input.readInt64();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          dataCollections_ = java.util.Collections.unmodifiableList(dataCollections_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }

    public static com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.class, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.Builder.class);
    }

    public interface DataCollectionOrBuilder extends
        // @@protoc_insertion_point(interface_extends:io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <pre>
       * 对应JSON结构中的data_collection字段
       * </pre>
       *
       * <code>string data_collection = 1;</code>
       * @return The dataCollection.
       */
      java.lang.String getDataCollection();
      /**
       * <pre>
       * 对应JSON结构中的data_collection字段
       * </pre>
       *
       * <code>string data_collection = 1;</code>
       * @return The bytes for dataCollection.
       */
      com.google.protobuf.ByteString
          getDataCollectionBytes();

      /**
       * <pre>
       * 对应JSON结构中的event_count字段
       * </pre>
       *
       * <code>int64 event_count = 2;</code>
       * @return The eventCount.
       */
      long getEventCount();
    }

    @java.lang.Override
    public boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public static final int STATUS_FIELD_NUMBER = 1;
    private volatile java.lang.Object status_;
    /**
     * <code>string status = 1;</code>
     * @return The status.
     */
    @java.lang.Override
    public java.lang.String getStatus() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        status_ = s;
        return s;
      }
    }
    /**
     * <code>string status = 1;</code>
     * @return The bytes for status.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getStatusBytes() {
      java.lang.Object ref = status_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        status_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    @java.lang.Override
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b =
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EVENT_COUNT_FIELD_NUMBER = 3;
    private long eventCount_;
    /**
     * <code>int64 event_count = 3;</code>
     * @return The eventCount.
     */
    @java.lang.Override
    public long getEventCount() {
      return eventCount_;
    }

    public static final int DATA_COLLECTIONS_FIELD_NUMBER = 4;
    private java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> dataCollections_;
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    @java.lang.Override
    public java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> getDataCollectionsList() {
      return dataCollections_;
    }
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    @java.lang.Override
    public java.util.List<? extends io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder>
        getDataCollectionsOrBuilderList() {
      return dataCollections_;
    }
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    @java.lang.Override
    public int getDataCollectionsCount() {
      return dataCollections_.size();
    }
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    @java.lang.Override
    public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDataCollections(int index) {
      return dataCollections_.get(index);
    }
    /**
     * <pre>
     * array对应repeated
     * </pre>
     *
     * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
     */
    @java.lang.Override
    public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder getDataCollectionsOrBuilder(
        int index) {
      return dataCollections_.get(index);
    }

    public static final int TS_MS_FIELD_NUMBER = 5;
    private long tsMs_;
    /**
     * <pre>
     * JSON中"optional": false对应非optional字段
     * </pre>
     *
     * <code>int64 ts_ms = 5;</code>
     * @return The tsMs.
     */
    @java.lang.Override
    public long getTsMs() {
      return tsMs_;
    }

    private byte memoizedIsInitialized = -1;

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata)) {
        return super.equals(obj);
      }
      io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata other = (io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata) obj;

      if (!getStatus()
          .equals(other.getStatus())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (getEventCount()
          != other.getEventCount()) return false;
      if (!getDataCollectionsList()
          .equals(other.getDataCollectionsList())) return false;
      if (getTsMs()
          != other.getTsMs()) return false;
      return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getStatusBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, status_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (eventCount_ != 0L) {
        output.writeInt64(3, eventCount_);
      }
      for (int i = 0; i < dataCollections_.size(); i++) {
        output.writeMessage(4, dataCollections_.get(i));
      }
      if (tsMs_ != 0L) {
        output.writeInt64(5, tsMs_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getStatusBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, status_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (eventCount_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, eventCount_);
      }
      for (int i = 0; i < dataCollections_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, dataCollections_.get(i));
      }
      if (tsMs_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, tsMs_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    /**
     * Protobuf type {@code io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection}
     */
    public static final class DataCollection extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection)
        DataCollectionOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use DataCollection.newBuilder() to construct.
      private DataCollection(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private DataCollection() {
        dataCollection_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new DataCollection();
      }

      public static com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor;
      }
      private DataCollection(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                dataCollection_ = s;
                break;
              }
              case 16: {

                eventCount_ = input.readInt64();
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }

      @java.lang.Override
      public com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.class, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder.class);
      }

      public static final int DATA_COLLECTION_FIELD_NUMBER = 1;
      private volatile java.lang.Object dataCollection_;
      /**
       * <pre>
       * 对应JSON结构中的data_collection字段
       * </pre>
       *
       * <code>string data_collection = 1;</code>
       * @return The dataCollection.
       */
      @java.lang.Override
      public java.lang.String getDataCollection() {
        java.lang.Object ref = dataCollection_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dataCollection_ = s;
          return s;
        }
      }
      /**
       * <pre>
       * 对应JSON结构中的data_collection字段
       * </pre>
       *
       * <code>string data_collection = 1;</code>
       * @return The bytes for dataCollection.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString
          getDataCollectionBytes() {
        java.lang.Object ref = dataCollection_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dataCollection_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int EVENT_COUNT_FIELD_NUMBER = 2;
      private long eventCount_;
      /**
       * <pre>
       * 对应JSON结构中的event_count字段
       * </pre>
       *
       * <code>int64 event_count = 2;</code>
       * @return The eventCount.
       */
      @java.lang.Override
      public long getEventCount() {
        return eventCount_;
      }

      private byte memoizedIsInitialized = -1;

      @java.lang.Override
      public boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getDataCollectionBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, dataCollection_);
        }
        if (eventCount_ != 0L) {
          output.writeInt64(2, eventCount_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getDataCollectionBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, dataCollection_);
        }
        if (eventCount_ != 0L) {
          size += com.google.protobuf.CodedOutputStream
            .computeInt64Size(2, eventCount_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection)) {
          return super.equals(obj);
        }
        io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection other = (io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection) obj;

        if (!getDataCollection()
            .equals(other.getDataCollection())) return false;
        if (getEventCount()
            != other.getEventCount()) return false;
        return unknownFields.equals(other.unknownFields);
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + DATA_COLLECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDataCollection().hashCode();
        hash = (37 * hash) + EVENT_COUNT_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
            getEventCount());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection)
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder {
        public static com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.class, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder.class);
        }

        // Construct using io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          dataCollection_ = "";

          eventCount_ = 0L;

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor;
        }

        @java.lang.Override
        public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDefaultInstanceForType() {
          return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.getDefaultInstance();
        }

        @java.lang.Override
        public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection build() {
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection buildPartial() {
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection result = new io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection(this);
          result.dataCollection_ = dataCollection_;
          result.eventCount_ = eventCount_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection) {
            return mergeFrom((io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection other) {
          if (other == io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.getDefaultInstance()) return this;
          if (!other.getDataCollection().isEmpty()) {
            dataCollection_ = other.dataCollection_;
            onChanged();
          }
          if (other.getEventCount() != 0L) {
            setEventCount(other.getEventCount());
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object dataCollection_ = "";
        /**
         * <pre>
         * 对应JSON结构中的data_collection字段
         * </pre>
         *
         * <code>string data_collection = 1;</code>
         * @return The dataCollection.
         */
        public java.lang.String getDataCollection() {
          java.lang.Object ref = dataCollection_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            dataCollection_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <pre>
         * 对应JSON结构中的data_collection字段
         * </pre>
         *
         * <code>string data_collection = 1;</code>
         * @return The bytes for dataCollection.
         */
        public com.google.protobuf.ByteString
            getDataCollectionBytes() {
          java.lang.Object ref = dataCollection_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b =
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            dataCollection_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <pre>
         * 对应JSON结构中的data_collection字段
         * </pre>
         *
         * <code>string data_collection = 1;</code>
         * @param value The dataCollection to set.
         * @return This builder for chaining.
         */
        public Builder setDataCollection(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }

          dataCollection_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 对应JSON结构中的data_collection字段
         * </pre>
         *
         * <code>string data_collection = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearDataCollection() {

          dataCollection_ = getDefaultInstance().getDataCollection();
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 对应JSON结构中的data_collection字段
         * </pre>
         *
         * <code>string data_collection = 1;</code>
         * @param value The bytes for dataCollection to set.
         * @return This builder for chaining.
         */
        public Builder setDataCollectionBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

          dataCollection_ = value;
          onChanged();
          return this;
        }

        private long eventCount_ ;
        /**
         * <pre>
         * 对应JSON结构中的event_count字段
         * </pre>
         *
         * <code>int64 event_count = 2;</code>
         * @return The eventCount.
         */
        @java.lang.Override
        public long getEventCount() {
          return eventCount_;
        }
        /**
         * <pre>
         * 对应JSON结构中的event_count字段
         * </pre>
         *
         * <code>int64 event_count = 2;</code>
         * @param value The eventCount to set.
         * @return This builder for chaining.
         */
        public Builder setEventCount(long value) {

          eventCount_ = value;
          onChanged();
          return this;
        }
        /**
         * <pre>
         * 对应JSON结构中的event_count字段
         * </pre>
         *
         * <code>int64 event_count = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearEventCount() {

          eventCount_ = 0L;
          onChanged();
          return this;
        }
        @java.lang.Override
        public Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection)
      }

      // @@protoc_insertion_point(class_scope:io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection)
      private static final io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection();
      }

      public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<DataCollection>
          PARSER = new com.google.protobuf.AbstractParser<DataCollection>() {
        @java.lang.Override
        public DataCollection parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataCollection(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<DataCollection> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<DataCollection> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + EVENT_COUNT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getEventCount());
      if (getDataCollectionsCount() > 0) {
        hash = (37 * hash) + DATA_COLLECTIONS_FIELD_NUMBER;
        hash = (53 * hash) + getDataCollectionsList().hashCode();
      }
      hash = (37 * hash) + TS_MS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTsMs());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }

    /**
     * Protobuf type {@code io.pixelsdb.pixels.sink.proto.TransactionMetadata}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.pixelsdb.pixels.sink.proto.TransactionMetadata)
        io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadataOrBuilder {
      public static com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.class, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.Builder.class);
      }

      // Construct using io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDataCollectionsFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        status_ = "";

        id_ = "";

        eventCount_ = 0L;

        if (dataCollectionsBuilder_ == null) {
          dataCollections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          dataCollectionsBuilder_.clear();
        }
        tsMs_ = 0L;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata getDefaultInstanceForType() {
        return io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.getDefaultInstance();
      }

      @java.lang.Override
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata build() {
        io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata buildPartial() {
        io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata result = new io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata(this);
        int from_bitField0_ = bitField0_;
        result.status_ = status_;
        result.id_ = id_;
        result.eventCount_ = eventCount_;
        if (dataCollectionsBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            dataCollections_ = java.util.Collections.unmodifiableList(dataCollections_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.dataCollections_ = dataCollections_;
        } else {
          result.dataCollections_ = dataCollectionsBuilder_.build();
        }
        result.tsMs_ = tsMs_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata) {
          return mergeFrom((io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata other) {
        if (other == io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.getDefaultInstance()) return this;
        if (!other.getStatus().isEmpty()) {
          status_ = other.status_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (other.getEventCount() != 0L) {
          setEventCount(other.getEventCount());
        }
        if (dataCollectionsBuilder_ == null) {
          if (!other.dataCollections_.isEmpty()) {
            if (dataCollections_.isEmpty()) {
              dataCollections_ = other.dataCollections_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDataCollectionsIsMutable();
              dataCollections_.addAll(other.dataCollections_);
            }
            onChanged();
          }
        } else {
          if (!other.dataCollections_.isEmpty()) {
            if (dataCollectionsBuilder_.isEmpty()) {
              dataCollectionsBuilder_.dispose();
              dataCollectionsBuilder_ = null;
              dataCollections_ = other.dataCollections_;
              bitField0_ = (bitField0_ & ~0x00000001);
              dataCollectionsBuilder_ =
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDataCollectionsFieldBuilder() : null;
            } else {
              dataCollectionsBuilder_.addAllMessages(other.dataCollections_);
            }
          }
        }
        if (other.getTsMs() != 0L) {
          setTsMs(other.getTsMs());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object status_ = "";
      /**
       * <code>string status = 1;</code>
       * @return The status.
       */
      public java.lang.String getStatus() {
        java.lang.Object ref = status_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          status_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       * @return The bytes for status.
       */
      public com.google.protobuf.ByteString
          getStatusBytes() {
        java.lang.Object ref = status_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          status_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string status = 1;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        status_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {

        status_ = getDefaultInstance().getStatus();
        onChanged();
        return this;
      }
      /**
       * <code>string status = 1;</code>
       * @param value The bytes for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        status_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b =
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }

        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {

        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);

        id_ = value;
        onChanged();
        return this;
      }

      private long eventCount_ ;
      /**
       * <code>int64 event_count = 3;</code>
       * @return The eventCount.
       */
      @java.lang.Override
      public long getEventCount() {
        return eventCount_;
      }
      /**
       * <code>int64 event_count = 3;</code>
       * @param value The eventCount to set.
       * @return This builder for chaining.
       */
      public Builder setEventCount(long value) {

        eventCount_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 event_count = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEventCount() {

        eventCount_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> dataCollections_ =
        java.util.Collections.emptyList();
      private void ensureDataCollectionsIsMutable() {
        if ((bitField0_ & 0x00000001) == 0) {
          dataCollections_ = new java.util.ArrayList<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection>(dataCollections_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder> dataCollectionsBuilder_;

      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> getDataCollectionsList() {
        if (dataCollectionsBuilder_ == null) {
          return java.util.Collections.unmodifiableList(dataCollections_);
        } else {
          return dataCollectionsBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public int getDataCollectionsCount() {
        if (dataCollectionsBuilder_ == null) {
          return dataCollections_.size();
        } else {
          return dataCollectionsBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection getDataCollections(int index) {
        if (dataCollectionsBuilder_ == null) {
          return dataCollections_.get(index);
        } else {
          return dataCollectionsBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder setDataCollections(
          int index, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection value) {
        if (dataCollectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataCollectionsIsMutable();
          dataCollections_.set(index, value);
          onChanged();
        } else {
          dataCollectionsBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder setDataCollections(
          int index, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder builderForValue) {
        if (dataCollectionsBuilder_ == null) {
          ensureDataCollectionsIsMutable();
          dataCollections_.set(index, builderForValue.build());
          onChanged();
        } else {
          dataCollectionsBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder addDataCollections(io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection value) {
        if (dataCollectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataCollectionsIsMutable();
          dataCollections_.add(value);
          onChanged();
        } else {
          dataCollectionsBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder addDataCollections(
          int index, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection value) {
        if (dataCollectionsBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDataCollectionsIsMutable();
          dataCollections_.add(index, value);
          onChanged();
        } else {
          dataCollectionsBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder addDataCollections(
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder builderForValue) {
        if (dataCollectionsBuilder_ == null) {
          ensureDataCollectionsIsMutable();
          dataCollections_.add(builderForValue.build());
          onChanged();
        } else {
          dataCollectionsBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder addDataCollections(
          int index, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder builderForValue) {
        if (dataCollectionsBuilder_ == null) {
          ensureDataCollectionsIsMutable();
          dataCollections_.add(index, builderForValue.build());
          onChanged();
        } else {
          dataCollectionsBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder addAllDataCollections(
          java.lang.Iterable<? extends io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection> values) {
        if (dataCollectionsBuilder_ == null) {
          ensureDataCollectionsIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, dataCollections_);
          onChanged();
        } else {
          dataCollectionsBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder clearDataCollections() {
        if (dataCollectionsBuilder_ == null) {
          dataCollections_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          dataCollectionsBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public Builder removeDataCollections(int index) {
        if (dataCollectionsBuilder_ == null) {
          ensureDataCollectionsIsMutable();
          dataCollections_.remove(index);
          onChanged();
        } else {
          dataCollectionsBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder getDataCollectionsBuilder(
          int index) {
        return getDataCollectionsFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder getDataCollectionsOrBuilder(
          int index) {
        if (dataCollectionsBuilder_ == null) {
          return dataCollections_.get(index);  } else {
          return dataCollectionsBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public java.util.List<? extends io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder>
           getDataCollectionsOrBuilderList() {
        if (dataCollectionsBuilder_ != null) {
          return dataCollectionsBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(dataCollections_);
        }
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder addDataCollectionsBuilder() {
        return getDataCollectionsFieldBuilder().addBuilder(
            io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.getDefaultInstance());
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder addDataCollectionsBuilder(
          int index) {
        return getDataCollectionsFieldBuilder().addBuilder(
            index, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.getDefaultInstance());
      }
      /**
       * <pre>
       * array对应repeated
       * </pre>
       *
       * <code>repeated .io.pixelsdb.pixels.sink.proto.TransactionMetadata.DataCollection data_collections = 4;</code>
       */
      public java.util.List<io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder>
           getDataCollectionsBuilderList() {
        return getDataCollectionsFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder>
          getDataCollectionsFieldBuilder() {
        if (dataCollectionsBuilder_ == null) {
          dataCollectionsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollection.Builder, io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata.DataCollectionOrBuilder>(
                  dataCollections_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          dataCollections_ = null;
        }
        return dataCollectionsBuilder_;
      }

      private long tsMs_ ;
      /**
       * <pre>
       * JSON中"optional": false对应非optional字段
       * </pre>
       *
       * <code>int64 ts_ms = 5;</code>
       * @return The tsMs.
       */
      @java.lang.Override
      public long getTsMs() {
        return tsMs_;
      }
      /**
       * <pre>
       * JSON中"optional": false对应非optional字段
       * </pre>
       *
       * <code>int64 ts_ms = 5;</code>
       * @param value The tsMs to set.
       * @return This builder for chaining.
       */
      public Builder setTsMs(long value) {

        tsMs_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * JSON中"optional": false对应非optional字段
       * </pre>
       *
       * <code>int64 ts_ms = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearTsMs() {

        tsMs_ = 0L;
        onChanged();
        return this;
      }
      @java.lang.Override
      public Builder setUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public Builder mergeUnknownFields(
              final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.pixelsdb.pixels.sink.proto.TransactionMetadata)
    }

    // @@protoc_insertion_point(class_scope:io.pixelsdb.pixels.sink.proto.TransactionMetadata)
    private static final io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata();
    }

    public static io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TransactionMetadata>
        PARSER = new com.google.protobuf.AbstractParser<TransactionMetadata>() {
      @java.lang.Override
      public TransactionMetadata parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionMetadata(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TransactionMetadata> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionMetadata> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.pixelsdb.pixels.sink.proto.TransactionMetadataValue.TransactionMetadata getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }
  static {
    java.lang.String[] descriptorData = {
      "\n\021transaction.proto\022\035io.pixelsdb.pixels." +
      "sink.proto\"\362\001\n\023TransactionMetadata\022\016\n\006st" +
      "atus\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\023\n\013event_count\030\003 " +
      "\001(\003\022[\n\020data_collections\030\004 \003(\0132A.io.pixel" +
      "sdb.pixels.sink.proto.TransactionMetadat" +
      "a.DataCollection\022\r\n\005ts_ms\030\005 \001(\003\032>\n\016DataC" +
      "ollection\022\027\n\017data_collection\030\001 \001(\t\022\023\n\013ev" +
      "ent_count\030\002 \001(\003B9\n\035io.pixelsdb.pixels.si" +
      "nk.protoB\030TransactionMetadataValueb\006prot" +
      "o3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor,
        new java.lang.String[] { "Status", "Id", "EventCount", "DataCollections", "TsMs", });
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor =
      internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_descriptor.getNestedTypes().get(0);
    internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_pixelsdb_pixels_sink_proto_TransactionMetadata_DataCollection_descriptor,
        new java.lang.String[] { "DataCollection", "EventCount", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
